tarification_entreprise:
    resource: "@tarificationEntrepriseBundle/Resources/config/routing.yml"
    prefix:   /

search_search:
    resource: "@SearchSearchBundle/Resources/config/routing.yml"
    prefix:   /

communes_admin:
    resource: "@CommunesAdminBundle/Resources/config/routing.yml"
    prefix:   /

communes:
    resource: "@CommunesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
     resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
     prefix: /admin

_sonata_admin:
     resource: .
     type: sonata_admin
     prefix: /admin
