<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartisPolitiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartisPolitiqueRepository extends EntityRepository
{
}
